SELECT  public.occurrence.auto_id AS id,
				public.occurrence.dwca_id,
				public.occurrence.sourcefileid,
				public.occurrence.occurrenceid,
				public.occurrence.scientificname AS canonical,
				public.occurrence.taxonrank as taxon_rank,
				public.occurrence.decimallatitude as latitude,
				public.occurrence.decimallongitude as longitude,
				public.occurrence.country as country_name,
				public.occurrence.county as county_name,
				public.occurrence.locality as locality,
				public.occurrence.syear as yearstart,
				public.occurrence.smonth as monthstart,
				public.occurrence.sday as daystart,
				public.occurrence.eyear as yearend,
				public.occurrence.emonth as monthend,
				public.occurrence.eday as dayend,
				public.occurrence.verbatimelevation as verbatim_elevation,
				public.occurrence.maximumelevationinmeters as maximum_elevation,
				public.occurrence.minimumelevationinmeters as minimum_elevation,
				public.occurrence.stateprovince as department_name,
				public.occurrence.kingdom as kingdom,
				public.occurrence.phylum as phylum,
				public.occurrence._class as class,
				public.occurrence._order as order,
				public.occurrence.family as family,
				public.occurrence.genus as genus,
				public.occurrence.species as species,
				public.occurrence.specificepithet as specific_epithet,
				public.occurrence.infraspecificepithet as infraspecific_epithet,
				public.publisher.auto_id as provider_id,
				public.publisher.name AS provider_name,
				public.publisher.description as provider_description,
				public.publisher.address as provider_address,
				public.publisher.city as provider_city,
				public.publisher.homepage as provider_website_url,
				public.publisher.logo_url as provider_logo_url,
				public.publisher.email as provider_email,
				public.publisher.phone as provider_phone,
				public.dwca_resource.id as resource_id,
				public.dwca_resource.name as resource_name,
				public.resource_metadata.title as resource_title,
				public.resource_metadata._abstract as resource_description,
				public.resource_metadata.intellectual_rights as resource_intellectual_rights,
				public.resource_metadata.citation as resource_citation,
				public.resource_metadata.resource_logo_url as resource_logo_url,
				public.resource_metadata.publication_date as resource_publication_date,
				public.resource_metadata.gbif_package_id AS resource_gbif_package_id,
				public.resource_metadata.alternate_identifier as resource_alternate_identifier,
				public.resource_metadata.language as resource_language,
				public.resource_metadata.keyword as resource_keyword,
        public.resource_metadata.keyword_thesaurus as resource_keyword_thesaurus,
				public.resource_metadata.hierarchy_level as resource_hierarchy_level,
				public.resource_metadata.collection_identifier as collection_identifier,
				public.resource_metadata.collection_name as collection_name,
				public.occurrence.collectioncode as collection_code,
				public.occurrence.institutioncode as institution_code,
				public.occurrence.catalognumber as catalog_number,
				public.occurrence.basisofrecord as basis_of_record_name,
				public.occurrence.recordedby as recorded_by,
				public.occurrence.habitat as habitat
FROM public.occurrence
JOIN public.dwca_resource ON public.occurrence.resource_id = public.dwca_resource.id
JOIN public.publisher ON public.dwca_resource.publisher_fkey = public.publisher.auto_id
JOIN public.resource_metadata ON public.dwca_resource.id = public.resource_metadata.dwca_resource_id
